CREATE TABLE IF NOT EXISTS cards (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    deck_id UUID NOT NULL,
    vocab VARCHAR(255) NOT NULL,
    kana VARCHAR(255) NOT NULL,
    meaning VARCHAR(255) NOT NULL,
    sentence VARCHAR(255) NOT NULL,
    english VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_cards_deck_id ON cards(deck_id);

ALTER TABLE cards
ADD CONSTRAINT fk_cards_deck_id_decks_id FOREIGN KEY(deck_id) REFERENCES decks(id);
